export const SEO_INSTRUCTIONS: Record<string, string> = {
    // Content
    google_index: 'Check robots.txt for "Disallow: /" and ensure the <meta name="robots" content="noindex"> tag is removed.',
    analytics: 'Install the Google Tag (gtag.js) in the <head> of your website pages.',
    speed: 'Compress images, minify CSS/JS files, and use a Content Delivery Network (CDN).',
    robots: 'Create a robots.txt file at your domain root (e.g., example.com/robots.txt) declaring crawl rules.',
    sitemap: 'Generate an XML sitemap and reference it in your robots.txt or submit it via Search Console.',
    friendly_url: 'Avoid dynamic parameters like "?id=123"; use human-readable slugs like "/seo-tips".',
    broken_links: 'Check for typos in your <a> tags and update any links pointing to deleted pages.',
    meta_desc: 'Add a <meta name="description" content="..."> tag between 120-160 characters.',
    meta_title: 'Update the <title> tag to be unique and include your primary keyword at the beginning.',
    keywords: 'Naturally integrate keywords into headings (H1, H2), meta descriptions, and the first paragraph.',
    duplicate: 'Use canonical tags or 301 redirects to point at the original source of the content.',
    canonical: 'Add a <link rel="canonical" href="..."> tag to tell search engines which URL is the preferred version.',
    alt_tags: 'Ensure every <img> tag has an alt="Description" attribute for accessibility and SEO.',
    responsive_img: 'Use "srcset" and "sizes" attributes or modern CSS (object-fit) to ensure images adapt to screen sizes.',
    modern_img: 'Convert JPEG/PNG images to WebP or AVIF for better compression without quality loss.',
    img_alt_check: 'Audit your code for <img> tags with missing alt attributes and add meaningful descriptions.',
    inline_css: 'Remove style="..." attributes from HTML elements and place them in an external .css file.',
    deprecated_html: 'Replace old tags with modern semantic HTML and CSS (e.g., use <div> with text-align: center instead of <center>).',
    css_minification: 'Use tools like PurgeCSS or CSSNano to remove whitespace and unused styles from your production CSS.',
    lcp: 'Prioritize loading the hero image or largest text block. Use font-display: swap and preconnect to important origins.',
    cls: 'Always include width and height attributes on images and video elements to reserve space.',
    h1_tags: 'Ensure there is only one <h1> tag and it contains the main topic of your page.',
    h2_tags: 'Divide your content into logical sections using <h2> subheadings.',
    html_size: 'Clean up unnecessary code, comments, and compress your HTML delivery using Gzip or Brotli.',
    img_caching: 'Set Cache-Control headers to at least 6 months (max-age=15552000) for static image assets.',
    js_caching: 'Set Cache-Control headers for JS files to max-age=31536000 (1 year) for better repeat performance.',
    css_caching: 'Configure your server to send "Cache-Control: public, max-age=31536000" for all CSS files.',
    error_404: 'Design a user-friendly 404.html page that includes a search bar and links to your homepage.',
    nofollow: 'Add rel="nofollow" to any external links that you don\'t want to pass "link juice" to.',
    favicon: 'Add a <link rel="icon" href="/favicon.ico"> to your <head> section.',

    // New checks
    og_tags: 'Add Open Graph meta tags (<meta property="og:title">, og:description, og:image, og:url) in your <head>.',
    twitter_card: 'Add <meta name="twitter:card" content="summary_large_image"> and related Twitter meta tags.',
    social_meta: 'Ensure og:image is at least 1200x630px for best display across social networks.',
    charset_declaration: 'Add <meta charset="UTF-8"> as the first tag inside <head>.',
    viewport: 'Add <meta name="viewport" content="width=device-width, initial-scale=1"> for proper mobile rendering.',
    doctype: 'Ensure your HTML starts with <!DOCTYPE html> (HTML5 doctype).',
    lang_attr: 'Add the lang attribute to <html> (e.g., <html lang="en">) for accessibility and localization.',
    https: 'Obtain an SSL certificate and redirect all HTTP traffic to HTTPS.',
    mixed_content: 'Change all resource URLs (images, scripts, stylesheets) loaded via HTTP to HTTPS.',
    http2: 'Configure your web server (nginx/Apache) or CDN to serve content over HTTP/2.',
    hsts: 'Add the Strict-Transport-Security response header with a long max-age directive.',
    safe_browsing: 'Check your site against Google\'s Safe Browsing API and remove any malicious content.',
    server_signature: 'Disable server signature in your web server config (ServerTokens Prod in Apache, server_tokens off in nginx).',
    directory_browsing: 'Disable directory listing in your server config (Options -Indexes in Apache).',
    plaintext_emails: 'Obfuscate email addresses using JavaScript or encode them with HTML entities.',
    unsafe_cross_origin: 'Add rel="noopener noreferrer" to all target="_blank" links to prevent tab-napping attacks.',
    spf_records: 'Add an SPF TXT record to your DNS: v=spf1 include:_spf.google.com ~all',
    ads_txt: 'Create an /ads.txt file at your domain root to authorize ad sellers.',
    gzip: 'Enable GZIP or Brotli compression on your web server to reduce HTML/CSS/JS transfer size.',
    page_cache: 'Use a server-side caching layer (Redis, Varnish, or CDN) to serve pre-built HTML pages.',
    cdn_usage: 'Use a CDN like Cloudflare, Fastly, or AWS CloudFront to serve assets from edge locations.',
    render_blocking: 'Add defer or async to non-critical <script> tags and use <link rel="preload"> for critical CSS.',
    flash_test: 'Remove all Adobe Flash content — Flash is deprecated and unsupported by all modern browsers.',
    nested_tables: 'Replace nested HTML table layouts with modern CSS Flexbox or Grid.',
    frameset: 'Remove framesets — use iframes sparingly or replace with modern CSS/JS alternatives.',
    url_redirects: 'Avoid redirect chains longer than 1 hop; use direct 301 redirects to the final destination.',
    noindex_tag: 'Remove <meta name="robots" content="noindex"> if you want the page to appear in search results.',
    canonical_tag: 'Ensure the canonical URL matches the current page URL exactly (protocol + trailing slash consistent).',
    meta_refresh: 'Remove <meta http-equiv="refresh"> tags and use proper server-side 301 redirects instead.',
    disallow_directive: 'Check that important pages like /products, /blog, and /about are not blocked in robots.txt.',
    structured_data: 'Add JSON-LD structured data (Schema.org) for FAQ, Product, Article, or Organization types.',
    js_error: 'Fix JavaScript errors visible in browser console — they can break functionality and harm UX.',
    console_errors: 'Resolve browser console errors — 404s for scripts and API failures impact performance.',
    dom_size: 'Reduce the number of DOM elements below 1500 — large DOMs slow down rendering significantly.',
    js_minification: 'Minify JavaScript files using tools like Terser or esbuild to reduce file size.',
    js_execution: 'Defer non-critical JavaScript and code-split large bundles to reduce main thread execution time.',
    image_aspect: 'Set explicit width and height on images to prevent layout shifts during loading.',
    image_metadata: 'Use meaningful filenames for images (e.g., red-shoes.jpg) to improve image search visibility.',
    spell_check: 'Proofread your content and use an automated spell-checker to fix common typos.',
    mobile_snapshot: 'Test your site on real mobile devices and use Chrome DevTools mobile simulation.',
    media_query: 'Use CSS media queries to ensure the layout adapts correctly across mobile, tablet and desktop.',
    keyword_cloud: 'Analyze keyword density — primary keywords should appear naturally at 1-3% of total word count.',
    keyword_usage: 'Include the primary keyword in the title, first H1, meta description, and first 100 words.',
    related_keywords: 'Use LSI (Latent Semantic Indexing) keywords and synonyms to improve topical relevance.',
    competitors: 'Analyze competitor pages to identify keyword gaps and content opportunities.',
    backlinks: 'Build quality backlinks from relevant, authoritative sites through guest posting and outreach.',
    inp: 'Reduce JavaScript execution time and long tasks to improve Interaction to Next Paint (INP < 200ms).',
    social_media_preview: 'Validate your Open Graph and Twitter Card tags using social media debugger tools.',
    page_objects: 'Minimize the total number of HTTP requests by bundling and combining assets where possible.',
    image_caching: 'Set far-future cache expiry headers for images to reduce repeat-visit load times.',
};
